from Story import name
chap3 = [
[0 , "~ CHAPTER 3 : Ai cũng có một câu chuyện tình ~ "],
[1 , "Ngày đầu ở Học viện trôi qua rất nhanh."],
[2 , "Ellie : Bái bai nhé, mai gặp lại! À Naib, lúc đi về nhớ để ý xem có ai theo dõi không, cẩn thận bị bắt vào ngõ ( ͡° ͜ʖ ͡°). - Ellie vừa đi cùng Hastur vừa nhìn lại, vẫy tay chào họ."],
[3 , "{} :...Ý cô ấy là sao? Lại tiên tri vớ vẩn à?".format (name)],
[4 , "Naib : Chơi lại tôi vố trước thôi, cậu không cần biết~ "],
[5 , "{} :...Tôi chỉ tự hỏi cô ấy làm gì ở nhà với... ừm....( ͡° ͜ʖ ͡°)".format(name)],
[6 , "Naib : Không can cậu nói ra =]"],
[7 , "Đúng là chỉ có bọn đầu óc đen tối mới hiểu nhau."],
[8 , "Naib : Thôi, tui về. Cậu thì sao?",
["1. Về nhà",9],
["2. Ở lại trường một lúc",11]],
[9 , "{} : Thì về nhà thôi.".format(name)],
[10 , "Naib : Vậy thì tạm biệt nhé, mai lại gặp!"],
[11 , "{} : Tớ ở trường dạo chơi một chút...".format(name)],
[12 , "Naib : {} ở riêng mà, thích nhỉ? Thích làm gì, về lúc nào cũng không ai mắng... Thôi bye, tui về không mẹ lại la.".format(name)],
[13 , "{} : Ừm, bye.".format(name)],
[14 , "Bạn rảo bước trên sân trường. Đi đâu giờ?",
["1. Thư viện",15],
["2. Khu khối H",],
["3. Sân sau của trường",]],
[15 , "Bạn bước vào Thư viện của trường. Đó là một thư viện nhìn khá cổ, tuy không rộng nhưng lại cao. Những giá sách gỗ xoáy thành hình xoắn ốc lên đến trần nhà, muốn lấy được những cuốn sách ở trên cùng phải bắc thang lên mà lấy."],
[16, "Bạn nhìn thấy một ai đó rất quen thuộc."],
[17 , "{} : Josephine? - Tuy cố hắng giọng xuống để không làm phiền mọi người trong thư viện, một  gì đó khiến bạn không làm được".format(name)],
[18 , "Josephine : Hửm? A, chẳng phải {} đấy ư? Chúng ta lại gặp nhau rồi!- Cô trả lời sau tiếng 'Suỵt' của mọi người. - Em làm gì ở đây vậy?".format(name),
["1.Stalk chị _|･ω･)-<3",19],
["2.Nghiên cứu về Học viện Desaulnier",21],
],
[19, "Josephine :...Moshi moshi, police desuka?"],
[20, "BAD ENDING 2 : Nước chè ở đồn rất ngon" ],
[21, "{} : Ừm, em muốn tìm hiểu thêm một chút về trường mình..."],
[22,"Josephine : Nếu vậy thì em ra tủ sách đằng kia nhé, dãy thứ 3 từ dưới lên là tìm được ngay thứ em muốn." ],
[23, "Bạn đi đến đó, lấy ra một quyển sách có đề 'HV Desaulnier và lịch sử huy hoàng' rồi ngồi ở ghế đối diện với Josephine."],
[24, "Josephine : Em biết không, em là đàn em khóa dưới đầu tiên chị gặp đấy!"],
[25, "{} : Dạ, vậy ạ..."],
[26, "...Josephine dường như nhận ra "],
]
